name: ruanchaves/b2w-reviews01
split: train
columns:
  - product_name
  - review_text
textcolumn: 'review_text'
ratingcolumn: 'overall_rating'
sentimentcolumn: 'sentiment'
testsize: 0.2
randomseed: 42
